### ISSUE TITLE
Core returns 403 error code for inactive companies. Should be 404 or 410.

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/rva#67]
Newly created users at UCLA Library Signage (Biomed) are unable to associate their google credentials and are caught in an endless loop.

Additional details are here:
https://trello.com/c/kAPpwSx1/377-openid-google-authentication-loop-for-ucla-library-signage-biomed

**Comment by alex-deaconu** [comment]
Upon investigation:
- Company in question was set to Inactive
Issue was fixed by setting the company status back to Active

- Core returns 403 error code for Inactive companies
Upon discussion, the error code is supposed to be 404 or 410. Both codes trigger User re-creation in the RVA (similar to new/deleted/inactive users). However, in this case the Inactive company had Active users which cannot be re-created. A job is supposed to run that sets Users to Inactive in the Inactive company, but we believe the Users were added after the fact.

Need to determine how the RVA (and the new apps) should react to Inactive companies.
