### ISSUE TITLE
Fonts in Common Header do not adhere to standard.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rva#86]
Compare fonts on:
rva.risevision.com common header
storage.risevision.com common header

Result:
Notice that the fonts do not match.

How it should work:
rva.risevision.com should have fonts that match the rest of our common header content.  

http://www.screencast.com/t/LrTPTeeUk

**Comment by ByronDarlison** [comment]
@alex-deaconu is this difficult to fix first thing today? Thanks

**Comment by alex-deaconu** [comment]
This issue is the result of 2 different stylesheets being used (CH stylesheet and RVA stylesheet). I cannot remove styles from the CH stylesheet, and removing styles from the RVA stylesheet could completely screw up the RVA spacing. I'll do my best to test this so no issues occur.

@ByronDarlison re: priority, I'm already working on another "priority" issue today: https://trello.com/c/jweGUzhO/269-company-transactions-and-country-code-conversion. 

Does this take priority over that?

Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu don't worry about this. Not worth it. Let's ship the new ux and it will be resolved. Thanks

**Comment by alex-deaconu** [comment]
@ByronDarlison sounds good, thanks for the simplification!

**Comment by ByronDarlison** [comment]
Won't fix
